/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplyAssessmentIdIndexRouteImport } from './routes/apply.$assessmentId.index'
import { Route as ApplyAssessmentIdSessionRouteImport } from './routes/apply.$assessmentId.session'

const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAssessmentIdIndexRoute = ApplyAssessmentIdIndexRouteImport.update({
  id: '/apply/$assessmentId/',
  path: '/apply/$assessmentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAssessmentIdSessionRoute =
  ApplyAssessmentIdSessionRouteImport.update({
    id: '/apply/$assessmentId/session',
    path: '/apply/$assessmentId/session',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/apply/$assessmentId/session': typeof ApplyAssessmentIdSessionRoute
  '/apply/$assessmentId/': typeof ApplyAssessmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/apply/$assessmentId/session': typeof ApplyAssessmentIdSessionRoute
  '/apply/$assessmentId': typeof ApplyAssessmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/apply/$assessmentId/session': typeof ApplyAssessmentIdSessionRoute
  '/apply/$assessmentId/': typeof ApplyAssessmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-account'
    | '/login'
    | '/apply/$assessmentId/session'
    | '/apply/$assessmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-account'
    | '/login'
    | '/apply/$assessmentId/session'
    | '/apply/$assessmentId'
  id:
    | '__root__'
    | '/create-account'
    | '/login'
    | '/apply/$assessmentId/session'
    | '/apply/$assessmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  ApplyAssessmentIdSessionRoute: typeof ApplyAssessmentIdSessionRoute
  ApplyAssessmentIdIndexRoute: typeof ApplyAssessmentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$assessmentId/': {
      id: '/apply/$assessmentId/'
      path: '/apply/$assessmentId'
      fullPath: '/apply/$assessmentId/'
      preLoaderRoute: typeof ApplyAssessmentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$assessmentId/session': {
      id: '/apply/$assessmentId/session'
      path: '/apply/$assessmentId/session'
      fullPath: '/apply/$assessmentId/session'
      preLoaderRoute: typeof ApplyAssessmentIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  ApplyAssessmentIdSessionRoute: ApplyAssessmentIdSessionRoute,
  ApplyAssessmentIdIndexRoute: ApplyAssessmentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
